- name: nginx and updating
  apt:
    name: nginx
    state: latest

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: replace html
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html

- name: replace default
  ansible.builtin.template:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: Restart nginx

- name: create exporter
  ansible.builtin.template:
    src: exporter
    dest: /etc/nginx/sites-enabled/exporter
  notify: Restart nginx