---
- name: Install HAproxy and Keepalived
  ansible.builtin.apt: 
    name: haproxy

- name: Copy HAproxy conf file
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Copy ha88 file
  ansible.builtin.template:
    src: ha88.j2
    dest: /usr/local/bin/ha88
    mode: 755

- name: HAproxy exporter
  ansible.builtin.apt: 
    name: prometheus-haproxy-exporter

- name: Copy HAproxy.scrape-uri
  ansible.builtin.template:
    src: haproxy.scrape-uri
    dest: /etc/default/prometheus-haproxy-exporter
  notify: 
    - restart haproxy
    - restart haproxy exporter

- name: Start HAproxy on boot
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - haproxy
    - prometheus-haproxy-exporter
