---
- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart influxdb exporter
  ansible.builtin.service:
    name: prometheus-influxdb-stats-exporter
    state: restarted
