---
- name: Move my.cnf.j2 file
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    owner: prometheus
    group: prometheus
    mode: 0600
  notify: Restart mysql_exporter
  no_log: true

- name: Move template
  ansible.builtin.template:
    src: prometheus-mysqld-exporter
    dest: /etc/default/prometheus-mysqld-exporter
  notify: Restart mysql_exporter

- name: prometheus mysql exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter
  register: prom_exporter_installed

- name: Start prometheus mysql exporters on boot
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes
