---
- name: prometheus mysql exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter
  register: prom_exporter_installed

- name: Move my.cnf.j2 file
  template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    owner: prometheus
    group: prometheus
    mode: u=r,g=,o=
  notify: Restart mysql_exporter

- name: Pause for 10 seconds
  pause: 
    seconds: 10
  when: prom_exporter_installed.changed

- name: Start prometheus mysql exporters on boot
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes