---
- name: restart grafana
  ansible.builtin.service:
    name: grafana-server
    state: restarted

- name: change admin pass
  ansible.builtin.shell: |
    sleep 30
    grafana-cli admin reset-admin-password {{grafana_password}} 
