---
- name: bind package
  ansible.builtin.apt:
    name: 
      - bind9
      - python3-dnspython 

- name: copy template named.conf.options.j2
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  no_log: true
  notify:
    restart bind

- name: copy template db.reily
  when: inventory_hostname in groups ['dns_master']
  ansible.builtin.template: 
    src: db.reily
    dest: /var/cache/bind/db.reily
    force: no
  notify:
    rndc reload

- name: copy template db.domain.reverse
  when: inventory_hostname in groups ['dns_master']
  ansible.builtin.template:
    src: db.domain.reverse
    dest: /var/cache/bind/db.reverse
    force: no
  notify:
    rndc reload

- name: copy template named.conf.local.j2
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify:
    restart bind
